### ISSUE TITLE
Docker hub image hasn't been updated.

### ISSUE THREAD

**Issue by alatiera** [rust-lang-nursery/docker-rust#13]
Even though the manifest is bumped to 1.22, the dockerhub repo is stuck at the 1.21 version.

**Comment by sfackler** [comment]
Just waiting on https://github.com/docker-library/official-images/pull/3742 to land.

**Comment by alatiera** [comment]
thanks for the update!

**Comment by phaero** [comment]
Do you know why the docker hub image takes so long to land? 

I mean ideally you would want an official image to be available the same day a new version of rust is released...

**Comment by sfackler** [comment]
Thanksgiving holiday probably.

**Comment by sfackler** [comment]
This has landed.
