### ISSUE TITLE
Cargo install updating registry forever

### ISSUE THREAD

**Issue by johnfercher** [rust-lang-nursery/docker-rust#26]
I'm having trouble to use rust in docker-rust. When I run **sudo docker build -t name .** the process runs forever.
  
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

Here my Dockerfile
```
FROM rust:1.23.0

WORKDIR /usr/src/myapp
COPY . .

RUN cargo install

CMD ["myapp"]
```

**Comment by sfackler** [comment]
What does "forever" mean? The registry index is ~200 MB that it will download when first updating.

**Comment by johnfercher** [comment]
It works, thank you.
