### ISSUE TITLE
Nightly version?

### ISSUE THREAD

**Issue by ghotiphud** [rust-lang-nursery/docker-rust#5]
I was trying to dockerize a Rocket app, and wanted to use the official Rust Docker image, but it seems there's no nightly?

Also, I'm new to Docker, so I may be mistaken.

**Comment by sfackler** [comment]
The Rust installs in the images are managed by rustup, so a simple approach would just be to run `rustup update nightly; rustup default nightly;` before building. You still have to pay the cost of downloading the full stable toolchain along with the image, though.

The official images have some [rules](https://github.com/docker-library/official-images#repeatability) around repeatability of images - not sure if there are exceptions for images intended to be non-repeatable like this one would be.

@yosifkit Is this a thing that's come up before in other images? For some background, Rust publishes nightly builds of the compiler and standard libraries which allow use of unstable functionality which is not available on the standard versioned releases. If we added a "nightly" image, the specific version of the distribution it ended up with would vary across builds every day or so.

**Comment by sfackler** [comment]
Cool - I believe all of the dependencies you're installing are already available on the buildpack image, bu the way: https://github.com/docker-library/buildpack-deps/blob/587934fb063d770d0611e94b57c9dd7a38edf928/stretch/Dockerfile#L3.

**Comment by ghotiphud** [comment]
Ha, you're probably right.  I was using `scorpil/rust:nightly` until I had everything actually working.

**Comment by yosifkit** [comment]
Any `nightly` or `dev` image in the official images would still need to maintain the repeatability aspect.  All builds make heavy use of docker build cache so if the `RUN` line does not change, the image would not change.  Base images get updates and cause dependent images to rebuild and we don't want those situations to cause a version bump to the main software of the image.  The only other time an image gets built is via a commit in official-images that changes the respective `library/` file.  `eggdrop` is one image that has a `develop` build that they update once in a while (like https://github.com/docker-library/official-images/pull/3051).

There is a related discussion in https://github.com/docker-library/official-images/issues/1281.

**Comment by sfackler** [comment]
Thanks @yosifkit, that all makes sense. The option of a `rust-lang/rust:nightly` rather than `rust:nightly` is interesting, and might be a good option!

**Comment by andre-richter** [comment]
Would also love to see a nightly image. I think the additional rust-lang namespace should not be a problem to for most people, it's just a matter of knowing where to find it.

**Comment by sfackler** [comment]
I've started building this out: https://hub.docker.com/r/sfackler/rust/. It should trigger a rebuild every night. Don't depend on it for anything real yet - I'll be deleting that image when it's moved over to an rust-lang org.

**Comment by andre-richter** [comment]
Thanks, appreciate it.

In case you are interested in a use case for using the container locally (also interactively) and caching cargo downloads and builds, kindly have a look my repository where I wrapped around your containers to achieve that:

https://github.com/andre-richter/docker-rust-persistent

**Comment by sfackler** [comment]
This is now set up: https://hub.docker.com/r/rustlang/rust/

**Comment by amouat** [comment]
I didn't realise it was so manual. I was figuring this could all be done with bots. Ok, I'll find a workaround. 

It just kinda feels like the official image should support nightly.

Thanks for the reply and your work on this anyway.
